[workspace]
members = ["oracle_feed", "market"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Verisight Team"]
license = "MIT"

[workspace.dependencies]
linera-sdk = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
async-trait = "0.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
